name: Shiro
options:
  bundleIdPrefix: com.wilton-garcia
targets:
  Shiro:
    type: application
    platform: iOS
    deploymentTarget: "16.4"
    sources: [Shiro]
    info:
      path: Shiro/Info.plist